"use client";
import {useState} from "react";
import {useSearchParams} from "next/navigation";
import {ShieldCheck,Loader2,CheckCircle2} from "lucide-react";
import {categories} from "@/lib/demo";
export default function ApplyForm({offers}:{offers:{id:string,slug:string,title:string,category:string}[]}){
 const params=useSearchParams();const [category,setCategory]=useState(params.get("category")||"");const [status,setStatus]=useState<"idle"|"sending"|"success">("idle");const [error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setStatus("sending");const form=new FormData(e.currentTarget);
  const payload={full_name:form.get("full_name"),email:form.get("email"),phone:form.get("phone"),category:form.get("category"),offer_slug:form.get("offer_slug"),purpose:form.get("purpose"),message:form.get("message"),consent:form.get("consent")==="on",honeypot:form.get("company_website")};
  try{const r=await fetch("/api/applications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(j.error||"Could not submit your enquiry");setStatus("success")}catch(err){setError(err instanceof Error?err.message:"Something went wrong");setStatus("idle")}
 }
 if(status==="success")return <div className="card mt-7 p-8 text-center"><CheckCircle2 size={52} className="mx-auto text-forest-600"/><h2 className="mt-4 text-2xl font-black">Application Received</h2><p className="mt-2 text-sm text-slate-500">Thank you. Your enquiry has been recorded.</p><button onClick={()=>setStatus("idle")} className="btn-primary mt-5">Submit Another</button></div>;
 return <form onSubmit={submit} className="card mt-7 space-y-5 p-5 sm:p-8"><div className="flex gap-3 rounded-2xl bg-forest-50 p-4 text-sm text-forest-900"><ShieldCheck className="shrink-0 text-forest-600" size={24}/><p>Your details are used to process your enquiry. We do not sell your personal information. Please review our Privacy/Terms information before submitting.</p></div>
 <div className="grid gap-5 sm:grid-cols-2"><label><span className="field-label">Full Name *</span><input name="full_name" required maxLength={120} className="form-input" placeholder="Your name"/></label><label><span className="field-label">Email Address *</span><input type="email" name="email" required maxLength={254} className="form-input" placeholder="name@example.com"/></label><label><span className="field-label">Mobile Number *</span><input name="phone" type="tel" required inputMode="numeric" minLength={10} maxLength={15} className="form-input" placeholder="10-digit mobile"/></label><label><span className="field-label">Product Category *</span><select className="form-input" required name="category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Choose a category</option>{categories.map(c=><option key={c.slug} value={c.slug}>{c.title}</option>)}</select></label></div>
 <label className="block"><span className="field-label">Product (Optional)</span><select className="form-input" name="offer_slug" defaultValue={params.get("product")||""} key={category}><option value="">General enquiry</option>{offers.filter(o=>o.category===category).map(o=><option key={o.slug} value={o.slug}>{o.title}</option>)}</select></label>
 <label className="block"><span className="field-label">Purpose</span><select name="purpose" className="form-input"><option value="">Choose purpose</option><option>Personal use</option><option>Business</option><option>Account opening</option><option>Investment</option><option>Insurance coverage</option><option>Other enquiry</option></select></label>
 <label className="block"><span className="field-label">Additional Details (Optional)</span><textarea name="message" maxLength={1000} rows={4} placeholder="Any questions?" className="form-input resize-y"/></label>
 <div className="hidden" aria-hidden="true"><label>Company website<input name="company_website" tabIndex={-1} autoComplete="off"/></label></div>
 <label className="flex items-start gap-3 text-xs leading-relaxed text-slate-600"><input type="checkbox" name="consent" required className="mt-0.5 h-4 w-4 accent-emerald-700"/>I agree to be contacted by NidhiGo Tamil about this enquiry via phone, SMS or email, and understand the information will be handled under the website terms. *</label>
 {error&&<div role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
 <button className="btn-primary w-full py-4" type="submit" disabled={status==="sending"}>{status==="sending"?<Loader2 size={18} className="animate-spin"/>:null}Submit Application</button>
 <p className="text-center text-xs text-slate-400">Your application is an enquiry, not a guarantee of product approval.</p></form>
}
